import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import Menu from "@/components/common/menu/menu";
import {ContactDrawerDialog} from "@/components/blocks/contact-drawer-dialog";
import LastPassFix from "@/components/blocks/last-pass-fix";
import OrientationProvider from "@/components/global/orientation.provider";
import {ReactNode} from "react";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode; }>) {
    return (
        <html lang="en">
            <body className={cn(inter.className)}>
                <OrientationProvider>
                    <LastPassFix>
                        <Menu/>
                        {children}
                        <ContactDrawerDialog/>
                    </LastPassFix>
                </OrientationProvider>
            </body>
        </html>
    );
}
